// Autogenerated by generate_dJdq_cpp.py -- do not edit by hand.
#include <ros/ros.h>
#include <Eigen/Eigen>

#include "mm_kinematics/kinematics.h"

namespace mm {

void Kinematics::calc_dJa_dq(const JointVector& q,
                             ArmJacobianMatrix& dJa_dtb,
                             ArmJacobianMatrix& dJa_dq1,
                             ArmJacobianMatrix& dJa_dq2,
                             ArmJacobianMatrix& dJa_dq3,
                             ArmJacobianMatrix& dJa_dq4,
                             ArmJacobianMatrix& dJa_dq5) {
    // Base variables
    double stb = std::sin(q(2));
    double ctb = std::cos(q(2));

    // Arm variables
    double sq1 = std::sin(q(3));
    double cq1 = std::cos(q(3));
    double sq2 = std::sin(q(4));
    double cq2 = std::cos(q(4));
    double sq3 = std::sin(q(5));
    double cq3 = std::cos(q(5));
    double sq4 = std::sin(q(6));
    double cq4 = std::cos(q(6));
    double sq5 = std::sin(q(7));
    double cq5 = std::cos(q(7));
    double sq6 = std::sin(q(8));
    double cq6 = std::cos(q(8));

  dJa_dtb(0,0) = a2*(sq1*stb - cq1*ctb)*cq2 - a3*(sq1*stb - cq1*ctb)*sq2*sq3 + a3*(sq1*stb - cq1*ctb)*cq2*cq3 + d4*(-sq1*ctb - stb*cq1) + d5*(((-sq1*stb + cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4) + d6*(((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + (-sq1*ctb - stb*cq1)*cq5) + d7*(((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + (-sq1*ctb - stb*cq1)*cq5);
  dJa_dtb(0,1) = -a2*(-sq1*ctb - stb*cq1)*sq2 - a3*(-sq1*ctb - stb*cq1)*sq2*cq3 - a3*(-sq1*ctb - stb*cq1)*sq3*cq2 + d5*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4) + d6*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa_dtb(0,2) = -a3*(-sq1*ctb - stb*cq1)*sq2*cq3 - a3*(-sq1*ctb - stb*cq1)*sq3*cq2 + d5*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4) + d6*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa_dtb(0,3) = d5*((-(-sq1*ctb - stb*cq1)*sq2*cq3 - (-sq1*ctb - stb*cq1)*sq3*cq2)*sq4 + ((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4) + d6*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa_dtb(0,4) = d6*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 + (sq1*stb - cq1*ctb)*sq5) + d7*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 + (sq1*stb - cq1*ctb)*sq5);
  dJa_dtb(0,5) = 0;
  dJa_dtb(1,0) = a2*(-sq1*ctb - stb*cq1)*cq2 - a3*(-sq1*ctb - stb*cq1)*sq2*sq3 + a3*(-sq1*ctb - stb*cq1)*cq2*cq3 + d4*(-sq1*stb + cq1*ctb) + d5*(((-sq1*ctb - stb*cq1)*sq2*cq3 + (-sq1*ctb - stb*cq1)*sq3*cq2)*cq4 + ((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4) + d6*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5) + d7*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5);
  dJa_dtb(1,1) = -a2*(-sq1*stb + cq1*ctb)*sq2 - a3*(-sq1*stb + cq1*ctb)*sq2*cq3 - a3*(-sq1*stb + cq1*ctb)*sq3*cq2 + d5*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa_dtb(1,2) = -a3*(-sq1*stb + cq1*ctb)*sq2*cq3 - a3*(-sq1*stb + cq1*ctb)*sq3*cq2 + d5*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa_dtb(1,3) = d5*((-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4 + ((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4) + d6*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5 + d7*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa_dtb(1,4) = d6*(((-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 + (-sq1*ctb - stb*cq1)*sq5) + d7*(((-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 + (-sq1*ctb - stb*cq1)*sq5);
  dJa_dtb(1,5) = 0;
  dJa_dtb(2,0) = 0;
  dJa_dtb(2,1) = 0;
  dJa_dtb(2,2) = 0;
  dJa_dtb(2,3) = 0;
  dJa_dtb(2,4) = 0;
  dJa_dtb(2,5) = 0;
  dJa_dtb(3,0) = 0;
  dJa_dtb(3,1) = -sq1*stb + cq1*ctb;
  dJa_dtb(3,2) = -sq1*stb + cq1*ctb;
  dJa_dtb(3,3) = -sq1*stb + cq1*ctb;
  dJa_dtb(3,4) = ((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4;
  dJa_dtb(3,5) = (-((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5;
  dJa_dtb(4,0) = 0;
  dJa_dtb(4,1) = sq1*ctb + stb*cq1;
  dJa_dtb(4,2) = sq1*ctb + stb*cq1;
  dJa_dtb(4,3) = sq1*ctb + stb*cq1;
  dJa_dtb(4,4) = ((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4;
  dJa_dtb(4,5) = (-((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 - ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*sq5 + (sq1*ctb + stb*cq1)*cq5;
  dJa_dtb(5,0) = 0;
  dJa_dtb(5,1) = 0;
  dJa_dtb(5,2) = 0;
  dJa_dtb(5,3) = 0;
  dJa_dtb(5,4) = 0;
  dJa_dtb(5,5) = 0;

  dJa_dq1(0,0) = a2*(sq1*stb - cq1*ctb)*cq2 - a3*(sq1*stb - cq1*ctb)*sq2*sq3 + a3*(sq1*stb - cq1*ctb)*cq2*cq3 + d4*(-sq1*ctb - stb*cq1) + d5*(((-sq1*stb + cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4) + d6*(((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + (-sq1*ctb - stb*cq1)*cq5) + d7*(((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + (-sq1*ctb - stb*cq1)*cq5);
  dJa_dq1(0,1) = -a2*(-sq1*ctb - stb*cq1)*sq2 - a3*(-sq1*ctb - stb*cq1)*sq2*cq3 - a3*(-sq1*ctb - stb*cq1)*sq3*cq2 + d5*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4) + d6*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa_dq1(0,2) = -a3*(-sq1*ctb - stb*cq1)*sq2*cq3 - a3*(-sq1*ctb - stb*cq1)*sq3*cq2 + d5*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4) + d6*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa_dq1(0,3) = d5*((-(-sq1*ctb - stb*cq1)*sq2*cq3 - (-sq1*ctb - stb*cq1)*sq3*cq2)*sq4 + ((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4) + d6*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa_dq1(0,4) = d6*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 + (sq1*stb - cq1*ctb)*sq5) + d7*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 + (sq1*stb - cq1*ctb)*sq5);
  dJa_dq1(0,5) = 0;
  dJa_dq1(1,0) = a2*(-sq1*ctb - stb*cq1)*cq2 - a3*(-sq1*ctb - stb*cq1)*sq2*sq3 + a3*(-sq1*ctb - stb*cq1)*cq2*cq3 + d4*(-sq1*stb + cq1*ctb) + d5*(((-sq1*ctb - stb*cq1)*sq2*cq3 + (-sq1*ctb - stb*cq1)*sq3*cq2)*cq4 + ((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4) + d6*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5) + d7*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5);
  dJa_dq1(1,1) = -a2*(-sq1*stb + cq1*ctb)*sq2 - a3*(-sq1*stb + cq1*ctb)*sq2*cq3 - a3*(-sq1*stb + cq1*ctb)*sq3*cq2 + d5*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa_dq1(1,2) = -a3*(-sq1*stb + cq1*ctb)*sq2*cq3 - a3*(-sq1*stb + cq1*ctb)*sq3*cq2 + d5*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa_dq1(1,3) = d5*((-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4 + ((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4) + d6*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5 + d7*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa_dq1(1,4) = d6*(((-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 + (-sq1*ctb - stb*cq1)*sq5) + d7*(((-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 + (-sq1*ctb - stb*cq1)*sq5);
  dJa_dq1(1,5) = 0;
  dJa_dq1(2,0) = 0;
  dJa_dq1(2,1) = 0;
  dJa_dq1(2,2) = 0;
  dJa_dq1(2,3) = 0;
  dJa_dq1(2,4) = 0;
  dJa_dq1(2,5) = 0;
  dJa_dq1(3,0) = 0;
  dJa_dq1(3,1) = -sq1*stb + cq1*ctb;
  dJa_dq1(3,2) = -sq1*stb + cq1*ctb;
  dJa_dq1(3,3) = -sq1*stb + cq1*ctb;
  dJa_dq1(3,4) = ((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4;
  dJa_dq1(3,5) = (-((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5;
  dJa_dq1(4,0) = 0;
  dJa_dq1(4,1) = sq1*ctb + stb*cq1;
  dJa_dq1(4,2) = sq1*ctb + stb*cq1;
  dJa_dq1(4,3) = sq1*ctb + stb*cq1;
  dJa_dq1(4,4) = ((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4;
  dJa_dq1(4,5) = (-((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 - ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*sq5 + (sq1*ctb + stb*cq1)*cq5;
  dJa_dq1(5,0) = 0;
  dJa_dq1(5,1) = 0;
  dJa_dq1(5,2) = 0;
  dJa_dq1(5,3) = 0;
  dJa_dq1(5,4) = 0;
  dJa_dq1(5,5) = 0;

  dJa_dq2(0,0) = -a2*(-sq1*ctb - stb*cq1)*sq2 - a3*(-sq1*ctb - stb*cq1)*sq2*cq3 - a3*(-sq1*ctb - stb*cq1)*sq3*cq2 + d5*((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + (-(-sq1*ctb - stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4 + ((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4 + ((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4)*sq5;
  dJa_dq2(0,1) = -a2*(-sq1*stb + cq1*ctb)*cq2 + a3*(-sq1*stb + cq1*ctb)*sq2*sq3 - a3*(-sq1*stb + cq1*ctb)*cq2*cq3 + d5*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa_dq2(0,2) = a3*(-sq1*stb + cq1*ctb)*sq2*sq3 - a3*(-sq1*stb + cq1*ctb)*cq2*cq3 + d5*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa_dq2(0,3) = d5*(((-sq1*stb + cq1*ctb)*sq2*sq3 - (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa_dq2(0,4) = d6*(((-sq1*stb + cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5 + d7*(((-sq1*stb + cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5;
  dJa_dq2(0,5) = 0;
  dJa_dq2(1,0) = -a2*(-sq1*stb + cq1*ctb)*sq2 - a3*(-sq1*stb + cq1*ctb)*sq2*cq3 - a3*(-sq1*stb + cq1*ctb)*sq3*cq2 + d5*((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4) + d6*(((-sq1*stb + cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq5 + d7*(((-sq1*stb + cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq5;
  dJa_dq2(1,1) = -a2*(sq1*ctb + stb*cq1)*cq2 + a3*(sq1*ctb + stb*cq1)*sq2*sq3 - a3*(sq1*ctb + stb*cq1)*cq2*cq3 + d5*((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5;
  dJa_dq2(1,2) = a3*(sq1*ctb + stb*cq1)*sq2*sq3 - a3*(sq1*ctb + stb*cq1)*cq2*cq3 + d5*((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5;
  dJa_dq2(1,3) = d5*(((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5;
  dJa_dq2(1,4) = d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + (-(-sq1*ctb - stb*cq1)*sq3*cq2 + (sq1*ctb + stb*cq1)*sq2*cq3)*cq4)*cq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + (-(-sq1*ctb - stb*cq1)*sq3*cq2 + (sq1*ctb + stb*cq1)*sq2*cq3)*cq4)*cq5;
  dJa_dq2(1,5) = 0;
  dJa_dq2(2,0) = 0;
  dJa_dq2(2,1) = -a2*sq2 - a3*sq2*cq3 - a3*sq3*cq2 + d5*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4) - d6*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa_dq2(2,2) = -a3*sq2*cq3 - a3*sq3*cq2 + d5*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4) - d6*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa_dq2(2,3) = d5*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4) - d6*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa_dq2(2,4) = -d6*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5 - d7*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5;
  dJa_dq2(2,5) = 0;
  dJa_dq2(3,0) = 0;
  dJa_dq2(3,1) = 0;
  dJa_dq2(3,2) = 0;
  dJa_dq2(3,3) = 0;
  dJa_dq2(3,4) = (-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4;
  dJa_dq2(3,5) = (-(-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq5;
  dJa_dq2(4,0) = 0;
  dJa_dq2(4,1) = 0;
  dJa_dq2(4,2) = 0;
  dJa_dq2(4,3) = 0;
  dJa_dq2(4,4) = ((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*sq4;
  dJa_dq2(4,5) = (-(-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 - ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4)*sq5;
  dJa_dq2(5,0) = 0;
  dJa_dq2(5,1) = 0;
  dJa_dq2(5,2) = 0;
  dJa_dq2(5,3) = 0;
  dJa_dq2(5,4) = (-sq2*sq3 + cq2*cq3)*sq4 + (sq2*cq3 + sq3*cq2)*cq4;
  dJa_dq2(5,5) = (-(-sq2*sq3 + cq2*cq3)*cq4 - (-sq2*cq3 - sq3*cq2)*sq4)*sq5;

  dJa_dq3(0,0) = -a3*(-sq1*ctb - stb*cq1)*sq2*cq3 - a3*(-sq1*ctb - stb*cq1)*sq3*cq2 + d5*((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + (-(-sq1*ctb - stb*cq1)*sq3*cq2 + (sq1*ctb + stb*cq1)*sq2*cq3)*sq4) + d6*(((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4)*sq5;
  dJa_dq3(0,1) = a3*(-sq1*stb + cq1*ctb)*sq2*sq3 - a3*(-sq1*stb + cq1*ctb)*cq2*cq3 + d5*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa_dq3(0,2) = a3*(-sq1*stb + cq1*ctb)*sq2*sq3 - a3*(-sq1*stb + cq1*ctb)*cq2*cq3 + d5*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa_dq3(0,3) = d5*(((-sq1*stb + cq1*ctb)*sq2*sq3 - (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 + (-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4) + d6*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa_dq3(0,4) = d6*(((-sq1*stb + cq1*ctb)*sq3*cq2 - (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5 + d7*(((-sq1*stb + cq1*ctb)*sq3*cq2 - (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5;
  dJa_dq3(0,5) = 0;
  dJa_dq3(1,0) = -a3*(-sq1*stb + cq1*ctb)*sq2*cq3 - a3*(-sq1*stb + cq1*ctb)*sq3*cq2 + d5*((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4) + d6*(((-sq1*stb + cq1*ctb)*sq3*cq2 - (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq5 + d7*(((-sq1*stb + cq1*ctb)*sq3*cq2 - (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq5;
  dJa_dq3(1,1) = a3*(sq1*ctb + stb*cq1)*sq2*sq3 - a3*(sq1*ctb + stb*cq1)*cq2*cq3 + d5*((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5;
  dJa_dq3(1,2) = a3*(sq1*ctb + stb*cq1)*sq2*sq3 - a3*(sq1*ctb + stb*cq1)*cq2*cq3 + d5*((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5;
  dJa_dq3(1,3) = d5*(((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4 + ((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5;
  dJa_dq3(1,4) = d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + (-(-sq1*ctb - stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + (-(-sq1*ctb - stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5;
  dJa_dq3(1,5) = 0;
  dJa_dq3(2,0) = 0;
  dJa_dq3(2,1) = -a3*sq2*cq3 - a3*sq3*cq2 + d5*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4) - d6*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa_dq3(2,2) = -a3*sq2*cq3 - a3*sq3*cq2 + d5*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4) - d6*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa_dq3(2,3) = d5*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4) - d6*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa_dq3(2,4) = -d6*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5 - d7*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5;
  dJa_dq3(2,5) = 0;
  dJa_dq3(3,0) = 0;
  dJa_dq3(3,1) = 0;
  dJa_dq3(3,2) = 0;
  dJa_dq3(3,3) = 0;
  dJa_dq3(3,4) = (-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4;
  dJa_dq3(3,5) = (-(-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq5;
  dJa_dq3(4,0) = 0;
  dJa_dq3(4,1) = 0;
  dJa_dq3(4,2) = 0;
  dJa_dq3(4,3) = 0;
  dJa_dq3(4,4) = ((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4;
  dJa_dq3(4,5) = (-(-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 - ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa_dq3(5,0) = 0;
  dJa_dq3(5,1) = 0;
  dJa_dq3(5,2) = 0;
  dJa_dq3(5,3) = 0;
  dJa_dq3(5,4) = (-sq2*sq3 + cq2*cq3)*sq4 + (sq2*cq3 + sq3*cq2)*cq4;
  dJa_dq3(5,5) = (-(-sq2*sq3 + cq2*cq3)*cq4 - (-sq2*cq3 - sq3*cq2)*sq4)*sq5;

  dJa_dq4(0,0) = d5*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4) + d6*(-(-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5 + d7*(-(-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa_dq4(0,1) = d5*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 - ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4) + d6*(-((-sq1*stb + cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*(-((-sq1*stb + cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa_dq4(0,2) = d5*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 - ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4) + d6*(-((-sq1*stb + cq1*ctb)*sq3*cq2 - (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*(-((-sq1*stb + cq1*ctb)*sq3*cq2 - (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa_dq4(0,3) = d5*(-(-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - ((-sq1*stb + cq1*ctb)*sq2*cq3 + (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - ((-sq1*stb + cq1*ctb)*sq2*cq3 + (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5;
  dJa_dq4(0,4) = d6*(-((-sq1*stb + cq1*ctb)*sq2*sq3 - (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 + ((-sq1*stb + cq1*ctb)*sq2*cq3 + (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*cq5 + d7*(-((-sq1*stb + cq1*ctb)*sq2*sq3 - (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 + ((-sq1*stb + cq1*ctb)*sq2*cq3 + (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*cq5;
  dJa_dq4(0,5) = 0;
  dJa_dq4(1,0) = d5*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4) + d6*(-(-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5 + d7*(-(-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa_dq4(1,1) = d5*(-((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 - (-(-sq1*ctb - stb*cq1)*sq3*cq2 + (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 - (-(-sq1*ctb - stb*cq1)*sq3*cq2 + (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5;
  dJa_dq4(1,2) = d5*(-((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 - (-(-sq1*ctb - stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 - (-(-sq1*ctb - stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5;
  dJa_dq4(1,3) = d5*(-(-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4) + d6*((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + d7*((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5;
  dJa_dq4(1,4) = d6*(-((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5 + d7*(-((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5;
  dJa_dq4(1,5) = 0;
  dJa_dq4(2,0) = 0;
  dJa_dq4(2,1) = d5*((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4) - d6*(-(-sq2*sq3 + cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*(-(-sq2*sq3 + cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa_dq4(2,2) = d5*((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4) - d6*(-(-sq2*sq3 + cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*(-(-sq2*sq3 + cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa_dq4(2,3) = d5*((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4) - d6*(-(-sq2*sq3 + cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*(-(-sq2*sq3 + cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa_dq4(2,4) = -d6*((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4)*cq5 - d7*((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4)*cq5;
  dJa_dq4(2,5) = 0;
  dJa_dq4(3,0) = 0;
  dJa_dq4(3,1) = 0;
  dJa_dq4(3,2) = 0;
  dJa_dq4(3,3) = 0;
  dJa_dq4(3,4) = (-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - ((-sq1*stb + cq1*ctb)*sq2*cq3 + (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4;
  dJa_dq4(3,5) = ((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa_dq4(4,0) = 0;
  dJa_dq4(4,1) = 0;
  dJa_dq4(4,2) = 0;
  dJa_dq4(4,3) = 0;
  dJa_dq4(4,4) = (-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4;
  dJa_dq4(4,5) = ((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa_dq4(5,0) = 0;
  dJa_dq4(5,1) = 0;
  dJa_dq4(5,2) = 0;
  dJa_dq4(5,3) = 0;
  dJa_dq4(5,4) = -(sq2*sq3 - cq2*cq3)*sq4 + (sq2*cq3 + sq3*cq2)*cq4;
  dJa_dq4(5,5) = (-(-sq2*sq3 + cq2*cq3)*cq4 + (sq2*cq3 + sq3*cq2)*sq4)*sq5;

  dJa_dq5(0,0) = d6*((-((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 - (-sq1*stb + cq1*ctb)*sq5) + d7*((-((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 - (-sq1*stb + cq1*ctb)*sq5);
  dJa_dq5(0,1) = d6*(-(-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5 + d7*(-(-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5;
  dJa_dq5(0,2) = d6*(-(-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5 + d7*(-(-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5;
  dJa_dq5(0,3) = d6*((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*cq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*cq5;
  dJa_dq5(0,4) = d6*(-(-(-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + (-sq1*ctb - stb*cq1)*cq5) + d7*(-(-(-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + (-sq1*ctb - stb*cq1)*cq5);
  dJa_dq5(0,5) = 0;
  dJa_dq5(1,0) = d6*((-((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 - ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 - (sq1*ctb + stb*cq1)*sq5) + d7*((-((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 - ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 - (sq1*ctb + stb*cq1)*sq5);
  dJa_dq5(1,1) = d6*(-(-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 - ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4)*cq5 + d7*(-(-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 - ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4)*cq5;
  dJa_dq5(1,2) = d6*(-(-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 - ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5 + d7*(-(-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 - ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5;
  dJa_dq5(1,3) = d6*((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5 + d7*((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5;
  dJa_dq5(1,4) = d6*(-(-(-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5) + d7*(-(-(-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5);
  dJa_dq5(1,5) = 0;
  dJa_dq5(2,0) = 0;
  dJa_dq5(2,1) = -d6*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5 - d7*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5;
  dJa_dq5(2,2) = -d6*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5 - d7*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5;
  dJa_dq5(2,3) = -d6*((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4)*cq5 - d7*((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4)*cq5;
  dJa_dq5(2,4) = d6*((-sq2*sq3 + cq2*cq3)*sq4 + (sq2*cq3 + sq3*cq2)*cq4)*sq5 + d7*((-sq2*sq3 + cq2*cq3)*sq4 + (sq2*cq3 + sq3*cq2)*cq4)*sq5;
  dJa_dq5(2,5) = 0;
  dJa_dq5(3,0) = 0;
  dJa_dq5(3,1) = 0;
  dJa_dq5(3,2) = 0;
  dJa_dq5(3,3) = 0;
  dJa_dq5(3,4) = 0;
  dJa_dq5(3,5) = (-(-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*cq5 - (sq1*ctb + stb*cq1)*sq5;
  dJa_dq5(4,0) = 0;
  dJa_dq5(4,1) = 0;
  dJa_dq5(4,2) = 0;
  dJa_dq5(4,3) = 0;
  dJa_dq5(4,4) = 0;
  dJa_dq5(4,5) = (-(-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 - (sq1*stb - cq1*ctb)*sq5;
  dJa_dq5(5,0) = 0;
  dJa_dq5(5,1) = 0;
  dJa_dq5(5,2) = 0;
  dJa_dq5(5,3) = 0;
  dJa_dq5(5,4) = 0;
  dJa_dq5(5,5) = (-(-sq2*sq3 + cq2*cq3)*sq4 - (sq2*cq3 + sq3*cq2)*cq4)*cq5;

}

} // namespace mm