// Autogenerated by generate_dJdq_cpp.py -- do not edit by hand.
#include <ros/ros.h>
#include <Eigen/Eigen>

#include "mm_kinematics/kinematics.h"

namespace mm {

void Kinematics::calc_dJa_dxb(const JointVector& q, ArmJacobianMatrix& dJa) {

    // Base joints
    double xb = q(0);
    double yb = q(1);
    double stb = std::sin(q(2));
    double ctb = std::cos(q(2));

    // Arm joints
    double sq1 = std::sin(q(3));
    double cq1 = std::cos(q(3));
    double sq2 = std::sin(q(4));
    double cq2 = std::cos(q(4));
    double sq3 = std::sin(q(5));
    double cq3 = std::cos(q(5));
    double sq4 = std::sin(q(6));
    double cq4 = std::cos(q(6));
    double sq5 = std::sin(q(7));
    double cq5 = std::cos(q(7));
    double sq6 = std::sin(q(8));
    double cq6 = std::cos(q(8));

  dJa(0,0) = 0;
  dJa(0,1) = 0;
  dJa(0,2) = 0;
  dJa(0,3) = 0;
  dJa(0,4) = 0;
  dJa(0,5) = 0;
  dJa(1,0) = 0;
  dJa(1,1) = 0;
  dJa(1,2) = 0;
  dJa(1,3) = 0;
  dJa(1,4) = 0;
  dJa(1,5) = 0;
  dJa(2,0) = 0;
  dJa(2,1) = 0;
  dJa(2,2) = 0;
  dJa(2,3) = 0;
  dJa(2,4) = 0;
  dJa(2,5) = 0;
  dJa(3,0) = 0;
  dJa(3,1) = 0;
  dJa(3,2) = 0;
  dJa(3,3) = 0;
  dJa(3,4) = 0;
  dJa(3,5) = 0;
  dJa(4,0) = 0;
  dJa(4,1) = 0;
  dJa(4,2) = 0;
  dJa(4,3) = 0;
  dJa(4,4) = 0;
  dJa(4,5) = 0;
  dJa(5,0) = 0;
  dJa(5,1) = 0;
  dJa(5,2) = 0;
  dJa(5,3) = 0;
  dJa(5,4) = 0;
  dJa(5,5) = 0;
}

void Kinematics::calc_dJa_dyb(const JointVector& q, ArmJacobianMatrix& dJa) {

    // Base joints
    double xb = q(0);
    double yb = q(1);
    double stb = std::sin(q(2));
    double ctb = std::cos(q(2));

    // Arm joints
    double sq1 = std::sin(q(3));
    double cq1 = std::cos(q(3));
    double sq2 = std::sin(q(4));
    double cq2 = std::cos(q(4));
    double sq3 = std::sin(q(5));
    double cq3 = std::cos(q(5));
    double sq4 = std::sin(q(6));
    double cq4 = std::cos(q(6));
    double sq5 = std::sin(q(7));
    double cq5 = std::cos(q(7));
    double sq6 = std::sin(q(8));
    double cq6 = std::cos(q(8));

  dJa(0,0) = 0;
  dJa(0,1) = 0;
  dJa(0,2) = 0;
  dJa(0,3) = 0;
  dJa(0,4) = 0;
  dJa(0,5) = 0;
  dJa(1,0) = 0;
  dJa(1,1) = 0;
  dJa(1,2) = 0;
  dJa(1,3) = 0;
  dJa(1,4) = 0;
  dJa(1,5) = 0;
  dJa(2,0) = 0;
  dJa(2,1) = 0;
  dJa(2,2) = 0;
  dJa(2,3) = 0;
  dJa(2,4) = 0;
  dJa(2,5) = 0;
  dJa(3,0) = 0;
  dJa(3,1) = 0;
  dJa(3,2) = 0;
  dJa(3,3) = 0;
  dJa(3,4) = 0;
  dJa(3,5) = 0;
  dJa(4,0) = 0;
  dJa(4,1) = 0;
  dJa(4,2) = 0;
  dJa(4,3) = 0;
  dJa(4,4) = 0;
  dJa(4,5) = 0;
  dJa(5,0) = 0;
  dJa(5,1) = 0;
  dJa(5,2) = 0;
  dJa(5,3) = 0;
  dJa(5,4) = 0;
  dJa(5,5) = 0;
}

void Kinematics::calc_dJa_dtb(const JointVector& q, ArmJacobianMatrix& dJa) {

    // Base joints
    double xb = q(0);
    double yb = q(1);
    double stb = std::sin(q(2));
    double ctb = std::cos(q(2));

    // Arm joints
    double sq1 = std::sin(q(3));
    double cq1 = std::cos(q(3));
    double sq2 = std::sin(q(4));
    double cq2 = std::cos(q(4));
    double sq3 = std::sin(q(5));
    double cq3 = std::cos(q(5));
    double sq4 = std::sin(q(6));
    double cq4 = std::cos(q(6));
    double sq5 = std::sin(q(7));
    double cq5 = std::cos(q(7));
    double sq6 = std::sin(q(8));
    double cq6 = std::cos(q(8));

  dJa(0,0) = a2*(sq1*stb - cq1*ctb)*cq2 - a3*(sq1*stb - cq1*ctb)*sq2*sq3 + a3*(sq1*stb - cq1*ctb)*cq2*cq3 + d4*(-sq1*ctb - stb*cq1) + d5*(((-sq1*stb + cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4) + d6*(((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + (-sq1*ctb - stb*cq1)*cq5) + d7*(((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + (-sq1*ctb - stb*cq1)*cq5);
  dJa(0,1) = -a2*(-sq1*ctb - stb*cq1)*sq2 - a3*(-sq1*ctb - stb*cq1)*sq2*cq3 - a3*(-sq1*ctb - stb*cq1)*sq3*cq2 + d5*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4) + d6*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa(0,2) = -a3*(-sq1*ctb - stb*cq1)*sq2*cq3 - a3*(-sq1*ctb - stb*cq1)*sq3*cq2 + d5*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4) + d6*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa(0,3) = d5*((-(-sq1*ctb - stb*cq1)*sq2*cq3 - (-sq1*ctb - stb*cq1)*sq3*cq2)*sq4 + ((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4) + d6*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa(0,4) = d6*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 + (sq1*stb - cq1*ctb)*sq5) + d7*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 + (sq1*stb - cq1*ctb)*sq5);
  dJa(0,5) = 0;
  dJa(1,0) = a2*(-sq1*ctb - stb*cq1)*cq2 - a3*(-sq1*ctb - stb*cq1)*sq2*sq3 + a3*(-sq1*ctb - stb*cq1)*cq2*cq3 + d4*(-sq1*stb + cq1*ctb) + d5*(((-sq1*ctb - stb*cq1)*sq2*cq3 + (-sq1*ctb - stb*cq1)*sq3*cq2)*cq4 + ((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4) + d6*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5) + d7*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5);
  dJa(1,1) = -a2*(-sq1*stb + cq1*ctb)*sq2 - a3*(-sq1*stb + cq1*ctb)*sq2*cq3 - a3*(-sq1*stb + cq1*ctb)*sq3*cq2 + d5*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa(1,2) = -a3*(-sq1*stb + cq1*ctb)*sq2*cq3 - a3*(-sq1*stb + cq1*ctb)*sq3*cq2 + d5*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa(1,3) = d5*((-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4 + ((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4) + d6*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5 + d7*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa(1,4) = d6*(((-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 + (-sq1*ctb - stb*cq1)*sq5) + d7*(((-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 + (-sq1*ctb - stb*cq1)*sq5);
  dJa(1,5) = 0;
  dJa(2,0) = 0;
  dJa(2,1) = 0;
  dJa(2,2) = 0;
  dJa(2,3) = 0;
  dJa(2,4) = 0;
  dJa(2,5) = 0;
  dJa(3,0) = 0;
  dJa(3,1) = -sq1*stb + cq1*ctb;
  dJa(3,2) = -sq1*stb + cq1*ctb;
  dJa(3,3) = -sq1*stb + cq1*ctb;
  dJa(3,4) = ((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4;
  dJa(3,5) = (-((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5;
  dJa(4,0) = 0;
  dJa(4,1) = sq1*ctb + stb*cq1;
  dJa(4,2) = sq1*ctb + stb*cq1;
  dJa(4,3) = sq1*ctb + stb*cq1;
  dJa(4,4) = ((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4;
  dJa(4,5) = (-((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 - ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*sq5 + (sq1*ctb + stb*cq1)*cq5;
  dJa(5,0) = 0;
  dJa(5,1) = 0;
  dJa(5,2) = 0;
  dJa(5,3) = 0;
  dJa(5,4) = 0;
  dJa(5,5) = 0;
}

void Kinematics::calc_dJa_dq1(const JointVector& q, ArmJacobianMatrix& dJa) {

    // Base joints
    double xb = q(0);
    double yb = q(1);
    double stb = std::sin(q(2));
    double ctb = std::cos(q(2));

    // Arm joints
    double sq1 = std::sin(q(3));
    double cq1 = std::cos(q(3));
    double sq2 = std::sin(q(4));
    double cq2 = std::cos(q(4));
    double sq3 = std::sin(q(5));
    double cq3 = std::cos(q(5));
    double sq4 = std::sin(q(6));
    double cq4 = std::cos(q(6));
    double sq5 = std::sin(q(7));
    double cq5 = std::cos(q(7));
    double sq6 = std::sin(q(8));
    double cq6 = std::cos(q(8));

  dJa(0,0) = a2*(sq1*stb - cq1*ctb)*cq2 - a3*(sq1*stb - cq1*ctb)*sq2*sq3 + a3*(sq1*stb - cq1*ctb)*cq2*cq3 + d4*(-sq1*ctb - stb*cq1) + d5*(((-sq1*stb + cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4) + d6*(((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + (-sq1*ctb - stb*cq1)*cq5) + d7*(((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + (-sq1*ctb - stb*cq1)*cq5);
  dJa(0,1) = -a2*(-sq1*ctb - stb*cq1)*sq2 - a3*(-sq1*ctb - stb*cq1)*sq2*cq3 - a3*(-sq1*ctb - stb*cq1)*sq3*cq2 + d5*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4) + d6*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa(0,2) = -a3*(-sq1*ctb - stb*cq1)*sq2*cq3 - a3*(-sq1*ctb - stb*cq1)*sq3*cq2 + d5*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4) + d6*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*ctb - stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa(0,3) = d5*((-(-sq1*ctb - stb*cq1)*sq2*cq3 - (-sq1*ctb - stb*cq1)*sq3*cq2)*sq4 + ((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4) + d6*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa(0,4) = d6*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 + (sq1*stb - cq1*ctb)*sq5) + d7*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 + (sq1*stb - cq1*ctb)*sq5);
  dJa(0,5) = 0;
  dJa(1,0) = a2*(-sq1*ctb - stb*cq1)*cq2 - a3*(-sq1*ctb - stb*cq1)*sq2*sq3 + a3*(-sq1*ctb - stb*cq1)*cq2*cq3 + d4*(-sq1*stb + cq1*ctb) + d5*(((-sq1*ctb - stb*cq1)*sq2*cq3 + (-sq1*ctb - stb*cq1)*sq3*cq2)*cq4 + ((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4) + d6*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5) + d7*(((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5);
  dJa(1,1) = -a2*(-sq1*stb + cq1*ctb)*sq2 - a3*(-sq1*stb + cq1*ctb)*sq2*cq3 - a3*(-sq1*stb + cq1*ctb)*sq3*cq2 + d5*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa(1,2) = -a3*(-sq1*stb + cq1*ctb)*sq2*cq3 - a3*(-sq1*stb + cq1*ctb)*sq3*cq2 + d5*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa(1,3) = d5*((-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4 + ((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4) + d6*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5 + d7*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa(1,4) = d6*(((-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 + (-sq1*ctb - stb*cq1)*sq5) + d7*(((-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 + (-sq1*ctb - stb*cq1)*sq5);
  dJa(1,5) = 0;
  dJa(2,0) = 0;
  dJa(2,1) = 0;
  dJa(2,2) = 0;
  dJa(2,3) = 0;
  dJa(2,4) = 0;
  dJa(2,5) = 0;
  dJa(3,0) = 0;
  dJa(3,1) = -sq1*stb + cq1*ctb;
  dJa(3,2) = -sq1*stb + cq1*ctb;
  dJa(3,3) = -sq1*stb + cq1*ctb;
  dJa(3,4) = ((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4;
  dJa(3,5) = (-((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5;
  dJa(4,0) = 0;
  dJa(4,1) = sq1*ctb + stb*cq1;
  dJa(4,2) = sq1*ctb + stb*cq1;
  dJa(4,3) = sq1*ctb + stb*cq1;
  dJa(4,4) = ((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4;
  dJa(4,5) = (-((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 - ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*sq5 + (sq1*ctb + stb*cq1)*cq5;
  dJa(5,0) = 0;
  dJa(5,1) = 0;
  dJa(5,2) = 0;
  dJa(5,3) = 0;
  dJa(5,4) = 0;
  dJa(5,5) = 0;
}

void Kinematics::calc_dJa_dq2(const JointVector& q, ArmJacobianMatrix& dJa) {

    // Base joints
    double xb = q(0);
    double yb = q(1);
    double stb = std::sin(q(2));
    double ctb = std::cos(q(2));

    // Arm joints
    double sq1 = std::sin(q(3));
    double cq1 = std::cos(q(3));
    double sq2 = std::sin(q(4));
    double cq2 = std::cos(q(4));
    double sq3 = std::sin(q(5));
    double cq3 = std::cos(q(5));
    double sq4 = std::sin(q(6));
    double cq4 = std::cos(q(6));
    double sq5 = std::sin(q(7));
    double cq5 = std::cos(q(7));
    double sq6 = std::sin(q(8));
    double cq6 = std::cos(q(8));

  dJa(0,0) = -a2*(-sq1*ctb - stb*cq1)*sq2 - a3*(-sq1*ctb - stb*cq1)*sq2*cq3 - a3*(-sq1*ctb - stb*cq1)*sq3*cq2 + d5*((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + (-(-sq1*ctb - stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4 + ((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4 + ((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4)*sq5;
  dJa(0,1) = -a2*(-sq1*stb + cq1*ctb)*cq2 + a3*(-sq1*stb + cq1*ctb)*sq2*sq3 - a3*(-sq1*stb + cq1*ctb)*cq2*cq3 + d5*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa(0,2) = a3*(-sq1*stb + cq1*ctb)*sq2*sq3 - a3*(-sq1*stb + cq1*ctb)*cq2*cq3 + d5*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa(0,3) = d5*(((-sq1*stb + cq1*ctb)*sq2*sq3 - (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa(0,4) = d6*(((-sq1*stb + cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5 + d7*(((-sq1*stb + cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5;
  dJa(0,5) = 0;
  dJa(1,0) = -a2*(-sq1*stb + cq1*ctb)*sq2 - a3*(-sq1*stb + cq1*ctb)*sq2*cq3 - a3*(-sq1*stb + cq1*ctb)*sq3*cq2 + d5*((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4) + d6*(((-sq1*stb + cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq5 + d7*(((-sq1*stb + cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq5;
  dJa(1,1) = -a2*(sq1*ctb + stb*cq1)*cq2 + a3*(sq1*ctb + stb*cq1)*sq2*sq3 - a3*(sq1*ctb + stb*cq1)*cq2*cq3 + d5*((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5;
  dJa(1,2) = a3*(sq1*ctb + stb*cq1)*sq2*sq3 - a3*(sq1*ctb + stb*cq1)*cq2*cq3 + d5*((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5;
  dJa(1,3) = d5*(((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5;
  dJa(1,4) = d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + (-(-sq1*ctb - stb*cq1)*sq3*cq2 + (sq1*ctb + stb*cq1)*sq2*cq3)*cq4)*cq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + (-(-sq1*ctb - stb*cq1)*sq3*cq2 + (sq1*ctb + stb*cq1)*sq2*cq3)*cq4)*cq5;
  dJa(1,5) = 0;
  dJa(2,0) = 0;
  dJa(2,1) = -a2*sq2 - a3*sq2*cq3 - a3*sq3*cq2 + d5*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4) - d6*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa(2,2) = -a3*sq2*cq3 - a3*sq3*cq2 + d5*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4) - d6*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa(2,3) = d5*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4) - d6*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa(2,4) = -d6*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5 - d7*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5;
  dJa(2,5) = 0;
  dJa(3,0) = 0;
  dJa(3,1) = 0;
  dJa(3,2) = 0;
  dJa(3,3) = 0;
  dJa(3,4) = (-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4;
  dJa(3,5) = (-(-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq5;
  dJa(4,0) = 0;
  dJa(4,1) = 0;
  dJa(4,2) = 0;
  dJa(4,3) = 0;
  dJa(4,4) = ((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*sq4;
  dJa(4,5) = (-(-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 - ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4)*sq5;
  dJa(5,0) = 0;
  dJa(5,1) = 0;
  dJa(5,2) = 0;
  dJa(5,3) = 0;
  dJa(5,4) = (-sq2*sq3 + cq2*cq3)*sq4 + (sq2*cq3 + sq3*cq2)*cq4;
  dJa(5,5) = (-(-sq2*sq3 + cq2*cq3)*cq4 - (-sq2*cq3 - sq3*cq2)*sq4)*sq5;
}

void Kinematics::calc_dJa_dq3(const JointVector& q, ArmJacobianMatrix& dJa) {

    // Base joints
    double xb = q(0);
    double yb = q(1);
    double stb = std::sin(q(2));
    double ctb = std::cos(q(2));

    // Arm joints
    double sq1 = std::sin(q(3));
    double cq1 = std::cos(q(3));
    double sq2 = std::sin(q(4));
    double cq2 = std::cos(q(4));
    double sq3 = std::sin(q(5));
    double cq3 = std::cos(q(5));
    double sq4 = std::sin(q(6));
    double cq4 = std::cos(q(6));
    double sq5 = std::sin(q(7));
    double cq5 = std::cos(q(7));
    double sq6 = std::sin(q(8));
    double cq6 = std::cos(q(8));

  dJa(0,0) = -a3*(-sq1*ctb - stb*cq1)*sq2*cq3 - a3*(-sq1*ctb - stb*cq1)*sq3*cq2 + d5*((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + (-(-sq1*ctb - stb*cq1)*sq3*cq2 + (sq1*ctb + stb*cq1)*sq2*cq3)*sq4) + d6*(((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4)*sq5;
  dJa(0,1) = a3*(-sq1*stb + cq1*ctb)*sq2*sq3 - a3*(-sq1*stb + cq1*ctb)*cq2*cq3 + d5*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa(0,2) = a3*(-sq1*stb + cq1*ctb)*sq2*sq3 - a3*(-sq1*stb + cq1*ctb)*cq2*cq3 + d5*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa(0,3) = d5*(((-sq1*stb + cq1*ctb)*sq2*sq3 - (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 + (-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4) + d6*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa(0,4) = d6*(((-sq1*stb + cq1*ctb)*sq3*cq2 - (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5 + d7*(((-sq1*stb + cq1*ctb)*sq3*cq2 - (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5;
  dJa(0,5) = 0;
  dJa(1,0) = -a3*(-sq1*stb + cq1*ctb)*sq2*cq3 - a3*(-sq1*stb + cq1*ctb)*sq3*cq2 + d5*((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4) + d6*(((-sq1*stb + cq1*ctb)*sq3*cq2 - (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq5 + d7*(((-sq1*stb + cq1*ctb)*sq3*cq2 - (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq5;
  dJa(1,1) = a3*(sq1*ctb + stb*cq1)*sq2*sq3 - a3*(sq1*ctb + stb*cq1)*cq2*cq3 + d5*((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5;
  dJa(1,2) = a3*(sq1*ctb + stb*cq1)*sq2*sq3 - a3*(sq1*ctb + stb*cq1)*cq2*cq3 + d5*((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5;
  dJa(1,3) = d5*(((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4 + ((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5;
  dJa(1,4) = d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + (-(-sq1*ctb - stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + (-(-sq1*ctb - stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5;
  dJa(1,5) = 0;
  dJa(2,0) = 0;
  dJa(2,1) = -a3*sq2*cq3 - a3*sq3*cq2 + d5*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4) - d6*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa(2,2) = -a3*sq2*cq3 - a3*sq3*cq2 + d5*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4) - d6*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa(2,3) = d5*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4) - d6*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa(2,4) = -d6*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5 - d7*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5;
  dJa(2,5) = 0;
  dJa(3,0) = 0;
  dJa(3,1) = 0;
  dJa(3,2) = 0;
  dJa(3,3) = 0;
  dJa(3,4) = (-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4;
  dJa(3,5) = (-(-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq5;
  dJa(4,0) = 0;
  dJa(4,1) = 0;
  dJa(4,2) = 0;
  dJa(4,3) = 0;
  dJa(4,4) = ((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4;
  dJa(4,5) = (-(-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 - ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa(5,0) = 0;
  dJa(5,1) = 0;
  dJa(5,2) = 0;
  dJa(5,3) = 0;
  dJa(5,4) = (-sq2*sq3 + cq2*cq3)*sq4 + (sq2*cq3 + sq3*cq2)*cq4;
  dJa(5,5) = (-(-sq2*sq3 + cq2*cq3)*cq4 - (-sq2*cq3 - sq3*cq2)*sq4)*sq5;
}

void Kinematics::calc_dJa_dq4(const JointVector& q, ArmJacobianMatrix& dJa) {

    // Base joints
    double xb = q(0);
    double yb = q(1);
    double stb = std::sin(q(2));
    double ctb = std::cos(q(2));

    // Arm joints
    double sq1 = std::sin(q(3));
    double cq1 = std::cos(q(3));
    double sq2 = std::sin(q(4));
    double cq2 = std::cos(q(4));
    double sq3 = std::sin(q(5));
    double cq3 = std::cos(q(5));
    double sq4 = std::sin(q(6));
    double cq4 = std::cos(q(6));
    double sq5 = std::sin(q(7));
    double cq5 = std::cos(q(7));
    double sq6 = std::sin(q(8));
    double cq6 = std::cos(q(8));

  dJa(0,0) = d5*(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4) + d6*(-(-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5 + d7*(-(-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa(0,1) = d5*((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 - ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4) + d6*(-((-sq1*stb + cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*(-((-sq1*stb + cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa(0,2) = d5*((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 - ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*sq4) + d6*(-((-sq1*stb + cq1*ctb)*sq3*cq2 - (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5 + d7*(-((-sq1*stb + cq1*ctb)*sq3*cq2 - (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*sq3 - (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq5;
  dJa(0,3) = d5*(-(-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4) + d6*((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - ((-sq1*stb + cq1*ctb)*sq2*cq3 + (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - ((-sq1*stb + cq1*ctb)*sq2*cq3 + (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5;
  dJa(0,4) = d6*(-((-sq1*stb + cq1*ctb)*sq2*sq3 - (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 + ((-sq1*stb + cq1*ctb)*sq2*cq3 + (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*cq5 + d7*(-((-sq1*stb + cq1*ctb)*sq2*sq3 - (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 + ((-sq1*stb + cq1*ctb)*sq2*cq3 + (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*cq5;
  dJa(0,5) = 0;
  dJa(1,0) = d5*(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4) + d6*(-(-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5 + d7*(-(-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa(1,1) = d5*(-((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 - (-(-sq1*ctb - stb*cq1)*sq3*cq2 + (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 - (-(-sq1*ctb - stb*cq1)*sq3*cq2 + (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq5;
  dJa(1,2) = d5*(-((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4) + d6*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 - (-(-sq1*ctb - stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + d7*(((-sq1*ctb - stb*cq1)*sq2*sq3 - (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 - (-(-sq1*ctb - stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5;
  dJa(1,3) = d5*(-(-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4) + d6*((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + d7*((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5;
  dJa(1,4) = d6*(-((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5 + d7*(-((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5;
  dJa(1,5) = 0;
  dJa(2,0) = 0;
  dJa(2,1) = d5*((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4) - d6*(-(-sq2*sq3 + cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*(-(-sq2*sq3 + cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa(2,2) = d5*((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4) - d6*(-(-sq2*sq3 + cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*(-(-sq2*sq3 + cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa(2,3) = d5*((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4) - d6*(-(-sq2*sq3 + cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5 - d7*(-(-sq2*sq3 + cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq5;
  dJa(2,4) = -d6*((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4)*cq5 - d7*((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4)*cq5;
  dJa(2,5) = 0;
  dJa(3,0) = 0;
  dJa(3,1) = 0;
  dJa(3,2) = 0;
  dJa(3,3) = 0;
  dJa(3,4) = (-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - ((-sq1*stb + cq1*ctb)*sq2*cq3 + (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4;
  dJa(3,5) = ((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*sq5;
  dJa(4,0) = 0;
  dJa(4,1) = 0;
  dJa(4,2) = 0;
  dJa(4,3) = 0;
  dJa(4,4) = (-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4;
  dJa(4,5) = ((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
  dJa(5,0) = 0;
  dJa(5,1) = 0;
  dJa(5,2) = 0;
  dJa(5,3) = 0;
  dJa(5,4) = -(sq2*sq3 - cq2*cq3)*sq4 + (sq2*cq3 + sq3*cq2)*cq4;
  dJa(5,5) = (-(-sq2*sq3 + cq2*cq3)*cq4 + (sq2*cq3 + sq3*cq2)*sq4)*sq5;
}

void Kinematics::calc_dJa_dq5(const JointVector& q, ArmJacobianMatrix& dJa) {

    // Base joints
    double xb = q(0);
    double yb = q(1);
    double stb = std::sin(q(2));
    double ctb = std::cos(q(2));

    // Arm joints
    double sq1 = std::sin(q(3));
    double cq1 = std::cos(q(3));
    double sq2 = std::sin(q(4));
    double cq2 = std::cos(q(4));
    double sq3 = std::sin(q(5));
    double cq3 = std::cos(q(5));
    double sq4 = std::sin(q(6));
    double cq4 = std::cos(q(6));
    double sq5 = std::sin(q(7));
    double cq5 = std::cos(q(7));
    double sq6 = std::sin(q(8));
    double cq6 = std::cos(q(8));

  dJa(0,0) = d6*((-((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 - (-sq1*stb + cq1*ctb)*sq5) + d7*((-((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 - (-sq1*stb + cq1*ctb)*sq5);
  dJa(0,1) = d6*(-(-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5 + d7*(-(-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5;
  dJa(0,2) = d6*(-(-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5 + d7*(-(-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5;
  dJa(0,3) = d6*((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*cq5 + d7*((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*cq5;
  dJa(0,4) = d6*(-(-(-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + (-sq1*ctb - stb*cq1)*cq5) + d7*(-(-(-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + (-sq1*ctb - stb*cq1)*cq5);
  dJa(0,5) = 0;
  dJa(1,0) = d6*((-((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 - ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 - (sq1*ctb + stb*cq1)*sq5) + d7*((-((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 - ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 - (sq1*ctb + stb*cq1)*sq5);
  dJa(1,1) = d6*(-(-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 - ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4)*cq5 + d7*(-(-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 - ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4)*cq5;
  dJa(1,2) = d6*(-(-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 - ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5 + d7*(-(-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 - ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5;
  dJa(1,3) = d6*((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5 + d7*((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5;
  dJa(1,4) = d6*(-(-(-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5) + d7*(-(-(-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5);
  dJa(1,5) = 0;
  dJa(2,0) = 0;
  dJa(2,1) = -d6*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5 - d7*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5;
  dJa(2,2) = -d6*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5 - d7*((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5;
  dJa(2,3) = -d6*((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4)*cq5 - d7*((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4)*cq5;
  dJa(2,4) = d6*((-sq2*sq3 + cq2*cq3)*sq4 + (sq2*cq3 + sq3*cq2)*cq4)*sq5 + d7*((-sq2*sq3 + cq2*cq3)*sq4 + (sq2*cq3 + sq3*cq2)*cq4)*sq5;
  dJa(2,5) = 0;
  dJa(3,0) = 0;
  dJa(3,1) = 0;
  dJa(3,2) = 0;
  dJa(3,3) = 0;
  dJa(3,4) = 0;
  dJa(3,5) = (-(-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*cq5 - (sq1*ctb + stb*cq1)*sq5;
  dJa(4,0) = 0;
  dJa(4,1) = 0;
  dJa(4,2) = 0;
  dJa(4,3) = 0;
  dJa(4,4) = 0;
  dJa(4,5) = (-(-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 - (sq1*stb - cq1*ctb)*sq5;
  dJa(5,0) = 0;
  dJa(5,1) = 0;
  dJa(5,2) = 0;
  dJa(5,3) = 0;
  dJa(5,4) = 0;
  dJa(5,5) = (-(-sq2*sq3 + cq2*cq3)*sq4 - (sq2*cq3 + sq3*cq2)*cq4)*cq5;
}

void Kinematics::calc_dJa_dq6(const JointVector& q, ArmJacobianMatrix& dJa) {

    // Base joints
    double xb = q(0);
    double yb = q(1);
    double stb = std::sin(q(2));
    double ctb = std::cos(q(2));

    // Arm joints
    double sq1 = std::sin(q(3));
    double cq1 = std::cos(q(3));
    double sq2 = std::sin(q(4));
    double cq2 = std::cos(q(4));
    double sq3 = std::sin(q(5));
    double cq3 = std::cos(q(5));
    double sq4 = std::sin(q(6));
    double cq4 = std::cos(q(6));
    double sq5 = std::sin(q(7));
    double cq5 = std::cos(q(7));
    double sq6 = std::sin(q(8));
    double cq6 = std::cos(q(8));

  dJa(0,0) = 0;
  dJa(0,1) = 0;
  dJa(0,2) = 0;
  dJa(0,3) = 0;
  dJa(0,4) = 0;
  dJa(0,5) = 0;
  dJa(1,0) = 0;
  dJa(1,1) = 0;
  dJa(1,2) = 0;
  dJa(1,3) = 0;
  dJa(1,4) = 0;
  dJa(1,5) = 0;
  dJa(2,0) = 0;
  dJa(2,1) = 0;
  dJa(2,2) = 0;
  dJa(2,3) = 0;
  dJa(2,4) = 0;
  dJa(2,5) = 0;
  dJa(3,0) = 0;
  dJa(3,1) = 0;
  dJa(3,2) = 0;
  dJa(3,3) = 0;
  dJa(3,4) = 0;
  dJa(3,5) = 0;
  dJa(4,0) = 0;
  dJa(4,1) = 0;
  dJa(4,2) = 0;
  dJa(4,3) = 0;
  dJa(4,4) = 0;
  dJa(4,5) = 0;
  dJa(5,0) = 0;
  dJa(5,1) = 0;
  dJa(5,2) = 0;
  dJa(5,3) = 0;
  dJa(5,4) = 0;
  dJa(5,5) = 0;
}


} // namespace mm
