#include "mm_motion_control/pose_error.h"

#include <Eigen/Eigen>

#include <mm_kinematics/kinematics.h>
#include <mm_math_util/linalg.h>


// Rotation error Jacobian is kept in its own file because the code is ugly.
// Generated by symbolic differentiation software; the math is not meant to be
// altered by hand.


namespace mm {

void rotation_error_jacobians(const JointVector& q,
                              Matrix3x9& Jn, Matrix3x9& Js, Matrix3x9& Ja) {
    double stb = std::sin(q(2));
    double ctb = std::cos(q(2));

    double sq1 = std::sin(q(3));
    double cq1 = std::cos(q(3));
    double sq2 = std::sin(q(4));
    double cq2 = std::cos(q(4));
    double sq3 = std::sin(q(5));
    double cq3 = std::cos(q(5));
    double sq4 = std::sin(q(6));
    double cq4 = std::cos(q(6));
    double sq5 = std::sin(q(7));
    double cq5 = std::cos(q(7));
    double sq6 = std::sin(q(8));
    double cq6 = std::cos(q(8));

    Jn(0,0) = 0;
    Jn(0,1) = 0;
    Jn(0,2) = ((((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 + (-sq1*stb + cq1*ctb)*sq5)*cq6 + ((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq6;
    Jn(0,3) = ((((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 + (-sq1*stb + cq1*ctb)*sq5)*cq6 + ((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq6;
    Jn(0,4) = ((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5*cq6 + (((-sq1*stb + cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq6;
    Jn(0,5) = ((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*cq5*cq6 + (((-sq1*stb + cq1*ctb)*sq3*cq2 - (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*sq6;
    Jn(0,6) = (-(-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*cq5*cq6 + (((-sq1*stb + cq1*ctb)*sq2*sq3 - (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq6;
    Jn(0,7) = (-((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 + (sq1*ctb + stb*cq1)*cq5)*cq6;
    Jn(0,8) = -(((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*cq5 + (sq1*ctb + stb*cq1)*sq5)*sq6 + (-(-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*cq6;
    Jn(1,0) = 0;
    Jn(1,1) = 0;
    Jn(1,2) = ((((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 + (sq1*ctb + stb*cq1)*sq5)*cq6 + ((-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq6;
    Jn(1,3) = ((((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 + (sq1*ctb + stb*cq1)*sq5)*cq6 + ((-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*sq6;
    Jn(1,4) = ((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4)*cq5*cq6 + ((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + (-(-sq1*ctb - stb*cq1)*sq3*cq2 + (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*sq6;
    Jn(1,5) = ((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5*cq6 + ((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + (-(-sq1*ctb - stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq6;
    Jn(1,6) = (-(-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq5*cq6 + (((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq6;
    Jn(1,7) = (-((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (sq1*stb - cq1*ctb)*cq5)*cq6;
    Jn(1,8) = -(((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 + (sq1*stb - cq1*ctb)*sq5)*sq6 + (-(-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq6;
    Jn(2,0) = 0;
    Jn(2,1) = 0;
    Jn(2,2) = 0;
    Jn(2,3) = 0;
    Jn(2,4) = ((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5*cq6 + ((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq6;
    Jn(2,5) = ((-sq2*sq3 + cq2*cq3)*cq4 + (-sq2*cq3 - sq3*cq2)*sq4)*cq5*cq6 + ((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq6;
    Jn(2,6) = (-(-sq2*sq3 + cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*sq6 + ((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4)*cq5*cq6;
    Jn(2,7) = -((-sq2*sq3 + cq2*cq3)*sq4 + (sq2*cq3 + sq3*cq2)*cq4)*sq5*cq6;
    Jn(2,8) = -((-sq2*sq3 + cq2*cq3)*sq4 + (sq2*cq3 + sq3*cq2)*cq4)*sq6*cq5 + ((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4)*cq6;

    Js(0,0) = 0;
    Js(0,1) = 0;
    Js(0,2) = (-(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 - (-sq1*stb + cq1*ctb)*sq5)*sq6 + ((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq6;
    Js(0,3) = (-(((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 - (-sq1*stb + cq1*ctb)*sq5)*sq6 + ((-(-sq1*ctb - stb*cq1)*cq2*cq3 - (sq1*ctb + stb*cq1)*sq2*sq3)*sq4 + ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*cq6;
    Js(0,4) = -((-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq6*cq5 + (((-sq1*stb + cq1*ctb)*sq2*cq3 - (sq1*stb - cq1*ctb)*sq3*cq2)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*cq6;
    Js(0,5) = -((-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq6*cq5 + (((-sq1*stb + cq1*ctb)*sq3*cq2 - (sq1*stb - cq1*ctb)*sq2*cq3)*sq4 + (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*cq4)*cq6;
    Js(0,6) = -(-(-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*sq6*cq5 + (((-sq1*stb + cq1*ctb)*sq2*sq3 - (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*cq6;
    Js(0,7) = (((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*sq5 - (sq1*ctb + stb*cq1)*cq5)*sq6;
    Js(0,8) = (-((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*cq5 - (sq1*ctb + stb*cq1)*sq5)*cq6 - (-(-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 + (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*sq6;
    Js(1,0) = 0;
    Js(1,1) = 0;
    Js(1,2) = (-(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 - (sq1*ctb + stb*cq1)*sq5)*sq6 + ((-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*cq6;
    Js(1,3) = (-(((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*cq5 - (sq1*ctb + stb*cq1)*sq5)*sq6 + ((-(-sq1*stb + cq1*ctb)*cq2*cq3 - (sq1*stb - cq1*ctb)*sq2*sq3)*sq4 + ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4)*cq6;
    Js(1,4) = -((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4)*sq6*cq5 + ((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + (-(-sq1*ctb - stb*cq1)*sq3*cq2 + (sq1*ctb + stb*cq1)*sq2*cq3)*sq4)*cq6;
    Js(1,5) = -((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 + ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq6*cq5 + ((-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*cq4 + (-(-sq1*ctb - stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq6;
    Js(1,6) = -(-(-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq6*cq5 + (((sq1*ctb + stb*cq1)*sq2*sq3 - (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq6;
    Js(1,7) = (((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 - (sq1*stb - cq1*ctb)*cq5)*sq6;
    Js(1,8) = (-((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 - (sq1*stb - cq1*ctb)*sq5)*cq6 - (-(-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 + (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq6;
    Js(2,0) = 0;
    Js(2,1) = 0;
    Js(2,2) = 0;
    Js(2,3) = 0;
    Js(2,4) = (-(-sq2*sq3 + cq2*cq3)*cq4 - (-sq2*cq3 - sq3*cq2)*sq4)*sq6*cq5 + ((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*cq6;
    Js(2,5) = (-(-sq2*sq3 + cq2*cq3)*cq4 - (-sq2*cq3 - sq3*cq2)*sq4)*sq6*cq5 + ((sq2*sq3 - cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*cq6;
    Js(2,6) = (-(-sq2*sq3 + cq2*cq3)*sq4 + (-sq2*cq3 - sq3*cq2)*cq4)*cq6 + (-(-sq2*sq3 + cq2*cq3)*cq4 + (sq2*cq3 + sq3*cq2)*sq4)*sq6*cq5;
    Js(2,7) = -(-(-sq2*sq3 + cq2*cq3)*sq4 - (sq2*cq3 + sq3*cq2)*cq4)*sq5*sq6;
    Js(2,8) = (-(-sq2*sq3 + cq2*cq3)*sq4 - (sq2*cq3 + sq3*cq2)*cq4)*cq5*cq6 - ((-sq2*sq3 + cq2*cq3)*cq4 - (sq2*cq3 + sq3*cq2)*sq4)*sq6;

    Ja(0,0) = 0;
    Ja(0,1) = 0;
    Ja(0,2) = (-((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5;
    Ja(0,3) = (-((-sq1*ctb - stb*cq1)*cq2*cq3 + (sq1*ctb + stb*cq1)*sq2*sq3)*cq4 - ((sq1*ctb + stb*cq1)*sq2*cq3 + (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*sq5 + (-sq1*stb + cq1*ctb)*cq5;
    Ja(0,4) = (-(-(-sq1*stb + cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq5;
    Ja(0,5) = (-(-(-sq1*stb + cq1*ctb)*sq3*cq2 + (sq1*stb - cq1*ctb)*sq2*cq3)*cq4 - (-(sq1*stb - cq1*ctb)*sq2*sq3 + (sq1*stb - cq1*ctb)*cq2*cq3)*sq4)*sq5;
    Ja(0,6) = ((-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*sq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*cq4)*sq5;
    Ja(0,7) = (-(-(-sq1*stb + cq1*ctb)*sq2*sq3 + (-sq1*stb + cq1*ctb)*cq2*cq3)*cq4 - (-(-sq1*stb + cq1*ctb)*sq2*cq3 - (-sq1*stb + cq1*ctb)*sq3*cq2)*sq4)*cq5 - (sq1*ctb + stb*cq1)*sq5;
    Ja(0,8) = 0;
    Ja(1,0) = 0;
    Ja(1,1) = 0;
    Ja(1,2) = (-((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 - ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*sq5 + (sq1*ctb + stb*cq1)*cq5;
    Ja(1,3) = (-((-sq1*stb + cq1*ctb)*cq2*cq3 + (sq1*stb - cq1*ctb)*sq2*sq3)*cq4 - ((sq1*stb - cq1*ctb)*sq2*cq3 + (sq1*stb - cq1*ctb)*sq3*cq2)*sq4)*sq5 + (sq1*ctb + stb*cq1)*cq5;
    Ja(1,4) = (-(-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 - ((-sq1*ctb - stb*cq1)*sq3*cq2 - (sq1*ctb + stb*cq1)*sq2*cq3)*cq4)*sq5;
    Ja(1,5) = (-(-(-sq1*ctb - stb*cq1)*sq2*sq3 + (-sq1*ctb - stb*cq1)*cq2*cq3)*sq4 - ((-sq1*ctb - stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
    Ja(1,6) = ((-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*sq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*cq4)*sq5;
    Ja(1,7) = (-(-(sq1*ctb + stb*cq1)*sq2*sq3 + (sq1*ctb + stb*cq1)*cq2*cq3)*cq4 - (-(sq1*ctb + stb*cq1)*sq2*cq3 - (sq1*ctb + stb*cq1)*sq3*cq2)*sq4)*cq5 - (sq1*stb - cq1*ctb)*sq5;
    Ja(1,8) = 0;
    Ja(2,0) = 0;
    Ja(2,1) = 0;
    Ja(2,2) = 0;
    Ja(2,3) = 0;
    Ja(2,4) = (-(-sq2*sq3 + cq2*cq3)*cq4 - (-sq2*cq3 - sq3*cq2)*sq4)*sq5;
    Ja(2,5) = (-(-sq2*sq3 + cq2*cq3)*cq4 - (-sq2*cq3 - sq3*cq2)*sq4)*sq5;
    Ja(2,6) = (-(-sq2*sq3 + cq2*cq3)*cq4 + (sq2*cq3 + sq3*cq2)*sq4)*sq5;
    Ja(2,7) = (-(-sq2*sq3 + cq2*cq3)*sq4 - (sq2*cq3 + sq3*cq2)*cq4)*cq5;
    Ja(2,8) = 0;
}

} // namespace mm
